name: Extract Boot or Vendor Boot

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'Direct Link for HyperOS Fastboot ROM (.tgz)'
        required: true
      file_to_extract:
        description: 'اختر الملف الذي تريد استخراجه'
        required: true
        type: choice
        options:
          - vendor_boot
          - boot

jobs:
  extract_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download and Extract
        run: |
          # تحديد اسم الملف المطلوب بناءً على اختيارك
          TARGET_FILE="${{ github.event.inputs.file_to_extract }}.img"
          echo "Target file is: $TARGET_FILE"

          # تحميل الروم
          echo "Downloading ROM..."
          curl -L "${{ github.event.inputs.rom_url }}" -o rom.tgz
          
          # البحث عن مسار الملف المختار داخل الأرشيف
          FILE_PATH=$(tar -tf rom.tgz | grep "$TARGET_FILE" | head -n 1)
          
          if [ -z "$FILE_PATH" ]; then
            echo "Error: $TARGET_FILE not found in the archive!"
            exit 1
          fi
          
          echo "Found file at: $FILE_PATH"
          
          # استخراج الملف وتجريده من المجلدات الطويلة ليكون في المجلد الرئيسي
          tar -xvf rom.tgz "$FILE_PATH" --strip-components=$(echo $FILE_PATH | tr -cd '/' | wc -c)
          
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.file_to_extract }}_image
          path: "*.img"
